### ISSUE TITLE
Highlight deprecation

### ISSUE THREAD

**Issue by TomasVotruba** [minetro/service-autoloader#1]
Hey, I wanted to inspire from this package, but I noticed in the middle of the README it is probably deprecated.

It is not very obvious, because it's not in the description of the package ("[CONTRIBUTTE] Automatic DIC service autoloader for Nette Framework (use @contributte)"), not in the name.

I'd recommend adding this note there, so other people notice right away.

Also, you can move it here https://github.com/DeprecatedPackages - composer works and people know.

Let me know what you think

**Comment by f3l1x** [comment]
I like an idea with DeprecatedPackages, one thing is missing, great logo. :-)

- https://www.iconfinder.com/search/?q=old
- https://www.iconfinder.com/icons/390441/gerontology_old_man_walker_icon#size=128

What do you think?

**Comment by TomasVotruba** [comment]
Good idea! You picked the same I wanted :+1:

**Comment by TomasVotruba** [comment]
I've sent you an admin invitation to the organization, so you can set it up when ready

**Comment by f3l1x** [comment]
@TomasVotruba Is it this one? (https://www.iconfinder.com/icons/390441/gerontology_old_man_walker_icon#size=128) I can buy it.

**Comment by TomasVotruba** [comment]
Yep

**Comment by f3l1x** [comment]
@TomasVotruba Done. Thanks. ;-)
